"""empty message

Revision ID: 541bb27c2545
Revises: 84ee7300f052
Create Date: 2021-03-07 21:05:56.694583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '541bb27c2545'
down_revision = '84ee7300f052'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'password')
    # ### end Alembic commands ###
